all:

  http_metas:
    content-type: text/html
    #activer si option ChromeFrame désactivée dans le .htaccess
    #X-UA-Compatible: IE=edge,chrome=1
    
  javascripts:
    - /theme/less/_framework/SPLessCss/Externals/js/polyfills/polyfills.js
    - /theme/less/_framework/SPLessCss/Externals/js/spLessGrid/spLessGrid.js